version: "3"
services:
  app:
    env_file:
      - .env
    container_name: colkie-backend
    restart: always
    build: .
    ports:
      - "$PORT:$PORT"
    links:
      - database
  database:
    image: postgres
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - database:/data/database
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    env_file:
      - .env

networks:
  default:
    name: colkie-network

volumes:
  database:
    driver: local